<a href="https://colab.research.google.com/github/MailsonFelipe/Analise_de_dadoss_pandas/blob/master/Mandalorian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **PoC utilizando KNN no Projeto Mandalorian**

**Importações**

In [19]:
import pandas as pd
import numpy as np
import sys

**Leitura dos dados (projetos)**

Há poucos dados para representar um projeto. Por isso, utilizei os campos abaixo (features), que achei mais importante. São 30 tuplas (representando 30 projetos)

In [11]:
# Primeira feature
area = ['externo','interno','externo','externo','interno','interno','externo','externo','interno','interno','interno','externo','externo',
        'externo','externo','externo','interno','externo','externo','interno','externo','externo','interno','externo','interno','externo','externo',
        'interno','externo','externo']

print('area '+str(len(area)))
# Segunda feature
enquadrabilidade = ['desenvolvimento experimental: software','desenvolvimento experimental: software','desenvolvimento experimental: software',
                    'formacao ou capacitacao profissional','servico cientifico e tecnologico de acessoria','desenvolvimento experimental: software',
                    'pesquisa basica','pesquisa aplicada','servico cientifico e tecnologico de acessoria','desenvolvimento experimental: automacao',
                    'pesquisa aplicada','formacao ou capacitacao profissional','servico cientifico e tecnologico de acessoria',
                    'formacao ou capacitacao profissional','desenvolvimento experimental: automacao','pesquisa aplicada','desenvolvimento experimental: software',
                    'pesquisa basica','desenvolvimento experimental: software','pesquisa basica','pesquisa aplicada','pesquisa basica','pesquisa basica',
                    'desenvolvimento experimental: software','desenvolvimento experimental: automacao','pesquisa basica','desenvolvimento experimental: software',
                    'pesquisa aplicada','pesquisa basica','formacao ou capacitacao profissional']
print('enquadrabilidade '+str(len(enquadrabilidade)))
# Teceira feature
tipo = ['ppb','ppb','ppb','lei de informatica','ppb','lei de informatica','lei de informatica','lei de informatica','lei de informatica',
        'lei de informatica','lei de informatica','ppb','lei de informatica','ppb','lei de informatica','lei de informatica','ppb','ppb',
        'ppb','ppb','ppb','lei de informatica','ppb','ppb','ppb','ppb','lei de informatica','ppb','ppb','lei de informatica']
print('tipo '+str(len(tipo)))

area 30
enquadrabilidade 30
tipo 30


**Tratamento dos dados**


A maioria dos algoritmos de aprendizado de máquina exigem dados de entrada numérica. Para tanto, é necessário mapear cada entrada em um número. E.g. externo: 0, interno: 1. 

In [57]:
# Importando LabelEncoder
from sklearn import preprocessing

# Criando labelEncoder
le = preprocessing.LabelEncoder()

# Convertendo strings em números
area_num = le.fit_transform(area [:20])
print(area_num)

enquad_num = le.fit_transform(enquadrabilidade [:20])
print(enquad_num)

tipo_num = le.fit_transform(tipo [:20])
print(tipo_num)

# Identificadores dos projetos
ids = []
for id in range (0, 30):
  ids.append(id)
ids = ids[:20]

# Combinando cada feature em uma quádrupla. Cada quádrupla representa um projeto
features=list(zip(area_num, enquad_num, tipo_num, ids))
print(features)

[0 1 0 0 1 1 0 0 1 1 1 0 0 0 0 0 1 0 0 1]
[1 1 1 2 5 1 4 3 5 0 3 2 5 2 0 3 1 4 1 4]
[1 1 1 0 1 0 0 0 0 0 0 1 0 1 0 0 1 1 1 1]
[(0, 1, 1, 0), (1, 1, 1, 1), (0, 1, 1, 2), (0, 2, 0, 3), (1, 5, 1, 4), (1, 1, 0, 5), (0, 4, 0, 6), (0, 3, 0, 7), (1, 5, 0, 8), (1, 0, 0, 9), (1, 3, 0, 10), (0, 2, 1, 11), (0, 5, 0, 12), (0, 2, 1, 13), (0, 0, 0, 14), (0, 3, 0, 15), (1, 1, 1, 16), (0, 4, 1, 17), (0, 1, 1, 18), (1, 4, 1, 19)]


**Criando um classificador KNN**

***1. Cálculo de distância (euclidiana):***

In [58]:
# Importando o módulo
import math
'''from sklearn.neighbors import KNeighborsClassifier

# Criando um objeto classificador, com K = 3
modelo = KNeighborsClassifier(n_neighbors=3)
label = []

for i in range (0, 30):
  label.append(features)
label = label[:20]

modelo.fit(features, label)

predicao = modelo.predict([[1,5,1]])'''

def distancia_euclidiana (feature_1, feature_2, tam):
    distancia = 0
    for i in range(tam):
        distancia += (feature_1[i] - feature_2[i])**2
    return math.sqrt(distancia)

# Exemplo
a = [4, -8, -9]
b = [2, -3, -5]

distancia_euclidiana(a, b, 3)

6.708203932499369

***2. Cálculo dos K vizinhos mais próximos***

In [60]:
def knn (nova_instancia, base_dados, k):
  distancias = [] # Distancias calculadas
  tam = len(nova_instancia) - 1
  
  for i in range(len(base_dados)):
    distancia = distancia_euclidiana(nova_instancia, base_dados[i], tam) # Distância do registro de teste a todos os outros.
    distancias.append((distancia, base_dados[i]))
  distancias.sort() # Ordenacao crescente
    
  vizinhos = []
  for j in range(k):
    vizinhos.append(distancias[j][1]) # Junta em vizinhos os k vizinhos mais próximos
      
  return vizinhos # Vizinhos mais próximos

teste = [0, 0, 0] # Novo projeto
knn(teste, features, 3)

[(0, 0, 0, 14), (0, 1, 1, 0), (0, 1, 1, 2)]

Note que os resultados são os projetos mais próximos, representados por seus ids (últimos dígidos da quádrupla). A ideia inicial é fazer o levantamento dos funcionários que mais participaram dos três projetos exibidos. Calcular a frequência deles e sugerir os mais atuantes. Esta é a ideia inicial, e pode ter melhorias.